### ISSUE TITLE
I probably need some help

### ISSUE THREAD

**Issue by pgroot91** [wp-forge/wp-geo-query#3]
First question would be does this also work in combination with meta_queries?

if so 

See below code example

```
$args = array(
	'post_type' => array('wpcm_vehicle'),
	'posts_per_page' => -1,
	'post_status' => 'publish',
	'suppress_filters' => true,
	'meta_query' => array(
		'relation' => 'AND',
		....
	), 
	'geo_query' => array(
		'lat'      => 0,
		'lng'      => 0,
		'distance' => 25,               // Default value is 25
		'units'    => 'miles',          // Default is miles, could also be 'mi', 'km', or 'kilometers'
		'lat_key'  => 'wpcm_lat',   // Default value is 'geo_latitude'
		'lng_key'  => 'wpcm_long',  // Default value is 'geo_longitude'
	),
);

$wp_query = new WP_Query( $args );
```

Added the following meta_keys and values to a post in the db `wpcm_lat` - `52.377956` and `wpcm_long` - `4.897070`.
Used the default geo_query so basically it should *NOT return that post.

Still it doesn't seem to have any effect the geo_query. I must be missing something silly since it also does not work without the meta_queries so that shouldn't be any issue i guess.

Any ideas what is wrong to point me in the right direction? 

Installed with composer and included the require `__DIR__ . 'vendor/autoload.php';` in my `functions.php` in my themes folder.

**Comment by wpscholar** [comment]
@pgroot91 The geo query functionality uses filters to work, so I think it is just the ``suppress_filters => true`` that is preventing it from working.

**Comment by pgroot91** [comment]
@wpscholar yes you seem to be right. 

But if i remove the `suppress_filters => true` the meta_queries won't work anymore. Guess to have a read and see why i need the suppress_filters for my filters to work.

**Comment by wpscholar** [comment]
Hmm, most likely there is a plugin doing something wrong and overwriting the `meta_query`.

**Comment by pgroot91** [comment]
I'm not sure if i'm doing something wrong...

in my theme template i do this only to get the start count of posts... 
```
$args = array(
	'post_type' => 'wpcm_vehicle',
	'status' => 'publish',
	'meta_query' => array(
	    array(
		   'key'     => 'wpcm_autowereld',
		   'value'   => '',
		   'compare' => '='
	   )
	)
);
$postTypes = new WP_Query($args);
$numberOfPosts = $postTypes->found_posts;	
```						
Then with ajax i update the live count when filters are applied and seems to work fine without any errors/warnings.

**Comment by wpscholar** [comment]
You're probably looking for something that leverages the [`pre_get_posts`](https://developer.wordpress.org/reference/hooks/pre_get_posts/) hook and then does something like this: `$query['meta_query'] = ...` (effectively trashing a passed-in meta query).  A one-off WP_Query wouldn't be causing the issue.

I'd give it a try with all other plugins inactive and see if it works then. If so, then just work backward by activating them one at a time to see what breaks it. If it isn't a plugin, then try with a default WordPress theme.

**Comment by pgroot91** [comment]
@wpscholar thanks for your help and your time!

Both the meta_query and geo_query seems to work now. Updated and removed some other packages via composer. Removed the `suppress_filters => true` and magicly it seems to work perfectly in harmony.
